blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Support & Questions
    url: https://discord.gg/TdBhmS4suY
    about: For general questions, discussions, or help — join the MachCore Discord.
